language: php
dist: trusty
sudo: false

services:
  - docker

php:
  - 7.2
  - 7.3

env:
  global:
    - COMPOSER_MEMORY_LIMIT=2G
    - SIMPLETEST_BASE_URL=http://localhost:8000
    - SIMPLETEST_DB_URL=mysql://tmp/mysql
  matrix:
    - JOB=job:check-coding-standards
    - JOB=job:run-unit-tests
    # - JOB=job:run-behat-tests

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update --$COMPOSER_CHANNEL
  - composer --version

install:
  - composer --verbose validate
  - composer --verbose install

before_script:
  - cp .travis/RoboFile.php .
  - cp .travis/.env .


# TODO: integrate with RoboFile task runner.
script:
  - vendor/bin/robo $JOB
  # - if [[ $RELEASE = dev ]]; then composer --verbose remove --no-update drupal/console; fi;
  # - if [[ $RELEASE = dev ]]; then composer --verbose require --no-update drupal/core:8.8.x-dev webflo/drupal-core-require-dev:8.8.x-dev; fi;
  # - if [[ $RELEASE = dev ]]; then composer --verbose update; fi;
  # - cd $TRAVIS_BUILD_DIR/web
  # - ./../vendor/bin/drush site-install --verbose --yes --db-url=$SIMPLETEST_DB_URL
  # - ./../vendor/bin/drush runserver $SIMPLETEST_BASE_URL &
  # - until curl -s $SIMPLETEST_BASE_URL; do true; done > /dev/null
  # # Skip core/tests/Drupal/Tests/ComposerIntegrationTest.php because web/ has no composer.json
  # # Ignore PageCache group temporarily, @see https://www.drupal.org/node/2770673
  # # Ignore Setup group temporarily, @see https://www.drupal.org/node/2962157
  # - ./../vendor/bin/phpunit -c core --testsuite unit --exclude-group Composer,DependencyInjection,PageCache,Setup
  # - ./../vendor/bin/drush
  # - if [[ $RELEASE = stable ]]; then ./../vendor/bin/drupal; fi;
