language: php
dist: trusty
sudo: false

services:
  - docker

php:
  - 7.2
  - 7.3

env:
  global:
    - COMPOSER_MEMORY_LIMIT=2G
    - SIMPLETEST_BASE_URL=http://127.0.0.1:8080
    - SIMPLETEST_DB_URL=mysql://tmp/mysql
    - NODE_VERSION=7.x
    - REMOTE_IMAGE_URL=491147561046.dkr.ecr.us-east-1.amazonaws.com/nypldrupal_phpnginx
    - secure: U5RJew207zn1HAEn/3HsXbWJegL4gY5pgh3BQlDmAPKAHaMvyE8KsYuw9bNquatrRSM4CCp2B1gpWWuR3odaz8A3wSkF3IGd1hrcHawok9Uo7hy46/kGnFp43nAXu6FXf3MAzNd385wSEdfFKdTuBto/TX8S7bMDWZD8aibqBZLYTxNMiHPXVMhyQXfEyro9x/BjpitqcukGiN55L1OEAeEvfdtzXGC7aeDe0sOu01jC6eC5LD9DCeUlDHBa2SZliYqSbXkRSrvyFcWP32Paa6hY8h3jx/PGmLyUQ0xIKBEKMK+aH69ywHQnGhT3m4unw40xItmG1xDLdMuir0YW1Yn1xyNMzQgnUXpHRSpAM0d4Zcjmf8Vvcmr3CNyby2JtxQF+NyMN4m78dInj7ThI743fIfqz3TM8aJALmNq1IUwNriRQOcWITfdQsHlAZ748qT7EUnZC2iKZiYcdBPc1XulmIav7YFuYjIRk9fAQsvpA5mf3rQz7+KxKrYw/Ww0K5QNB82kcAHcsX+DvDatlk89QuLKraJ4c29O5Gs4IqR6ZRJTN3BjHm9Nv82KmRjaKgKbPblZR78bWWiumV5a6tl5ZxdghF5wvcMpdCUiE5mvY++DkQZ+u4T+IAIg3RqeZpBNG2MRGILt/kMbDfvrqGRDZo7FOUWJlhmhA7QS0H2o=
  matrix:
    - JOB=job:check-coding-standards
    # - JOB=job:run-unit-tests
    # - JOB=job:run-behat-tests

before_install:
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update --$COMPOSER_CHANNEL
  - composer --version
  - sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -
  - sudo apt-get install -y nodejs

install:
  - composer --verbose validate
  - composer --verbose install --prefer-dist --no-interaction

before_script:
  - cp .travis/RoboFile.php .
  - cp .travis/.env .

script:
  - vendor/bin/robo $JOB
  - cd web/themes/custom/nypl_emulsify
  - npm install
  - ./node_modules/gulp/bin/gulp.js build

after_success:
  - cd $HOME
  - provisioning/travis/build_for_aws.sh
  - provisioning/travis/deploy_on_aws.sh

after_failure:
  - if [ -f $HOME/server.log ] ; then echo "Server log:" && cat $HOME/server.log ; fi

after_script:
  - rm -rf $HOME/server.log
  - rm -rf $HOME/web/themes/custom/nypl_emulsify/pattern-lab
  - rm -rf $HOME/web/themes/custom/nypl_emulsify/node_modules

notifications:
  email:
    recipients:
      gregorykallenberg@nypl.org
    on_success: always
    on_failure: always