language: php
dist: trusty
sudo: false

services:
- docker

php:
- 7.2
- 7.3

env:
  global:
  - SIMPLETEST_BASE_URL=http://127.0.0.1:8080
  - SIMPLETEST_DB_URL=mysql://tmp/mysql
  # Node version for nypl_emulsify asset build
  - NODE_VERSION=7.x
  # Travis variables for AWS
  - REMOTE_IMAGE_URL=491147561046.dkr.ecr.us-east-1.amazonaws.com/nypldrupal_phpnginx
  - secure: U5RJew207zn1HAEn/3HsXbWJegL4gY5pgh3BQlDmAPKAHaMvyE8KsYuw9bNquatrRSM4CCp2B1gpWWuR3odaz8A3wSkF3IGd1hrcHawok9Uo7hy46/kGnFp43nAXu6FXf3MAzNd385wSEdfFKdTuBto/TX8S7bMDWZD8aibqBZLYTxNMiHPXVMhyQXfEyro9x/BjpitqcukGiN55L1OEAeEvfdtzXGC7aeDe0sOu01jC6eC5LD9DCeUlDHBa2SZliYqSbXkRSrvyFcWP32Paa6hY8h3jx/PGmLyUQ0xIKBEKMK+aH69ywHQnGhT3m4unw40xItmG1xDLdMuir0YW1Yn1xyNMzQgnUXpHRSpAM0d4Zcjmf8Vvcmr3CNyby2JtxQF+NyMN4m78dInj7ThI743fIfqz3TM8aJALmNq1IUwNriRQOcWITfdQsHlAZ748qT7EUnZC2iKZiYcdBPc1XulmIav7YFuYjIRk9fAQsvpA5mf3rQz7+KxKrYw/Ww0K5QNB82kcAHcsX+DvDatlk89QuLKraJ4c29O5Gs4IqR6ZRJTN3BjHm9Nv82KmRjaKgKbPblZR78bWWiumV5a6tl5ZxdghF5wvcMpdCUiE5mvY++DkQZ+u4T+IAIg3RqeZpBNG2MRGILt/kMbDfvrqGRDZo7FOUWJlhmhA7QS0H2o=
  # Travis variables for Pantheon
  - DEFAULT_BRANCH=pantheon
  - PSITE='nypl-docker'
  - PENV='dev'
  - PHOST='https://$PENV-$PSITE.pantheonsite.io'
  - secure: oSr23rF56mffvGShnM7S4X2oBHAtFTHZ1F2QSRBLKVP4M8tlq9V2clG/ykxCFAMfOpFWiR6LYOmsMN3wVPV3VeE/5K/zZtvClgzYEBiUzjCU4Owo47ZjzbkZGoySWue/4+HdXVeuqHQgdkW8XqVbxDLe8xiKSeErhrfB4MujXnRwMFVNQof4Dj+YGtMaL4S8SdWG7KPnXLuEdPMEWhblfsuW6t7DVblxzlueVvaopfO+fgAVhHYkEBADLcURoRWy/fSz/jF2i4BW2ZkNMS8wKQQ1dLnuYQtpWnPCG+zgACWDze4OYdqH3HCZJDus5WZxFwz1TzBWrtCD9rR9K+3uI/Yy3JIoUe1lz4zkrSQodVo3SrzhkYKtOCVhJdkqA2Np2DjdwlVwYoT/3Xl2YReQFYN1Ri82WoMrrlSgEyM2llJ8kUqwoFC3fwqyjEV5DsGsby1PbLT45R3yhZzXK/FogD3MnoIsha1g7zGfP0ml2++YVSmfrsf8opZwmuXv/QUnFy3VgcwtINf6sVDWJCj4xY3bp+x1eC2jvOHtTALC/rKM26gNUpio3eJif0OIZqN236nNCH7nHegBU/WrQuRzUacreGdxMJoNsR4mSwMEOIREzGDhaQZE2Qd1psTbiDS3Y1GvmAN0uKEKBliwaZLv9J2CdYtgw7QlPR5wIlGn4w8=
  matrix:
  - JOB=job:check-coding-standards
  # - JOB=job:run-unit-tests
  # - JOB=job:run-behat-tests

before_install:
  # Setup password-less passphrase for Pantheon
  - openssl aes-256-cbc -K $encrypted_8a30a4e5a3eb_key -iv $encrypted_8a30a4e5a3eb_iv -in travis-ci-key.enc -out travis-ci-key -d
  - cp travis-ci-key ~/.ssh/id_rsa
  - chmod 0600 ~/.ssh/id_rsa
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update --$COMPOSER_CHANNEL
  - composer --version
  - sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -
  - sudo apt-get install -y nodejs

install:
  - composer --verbose validate
  - composer install --prefer-dist --no-interaction -q

before_script:
  - bin/disable-php-email
  - cp .travis/RoboFile.php .
  - cp .travis/.env .

script:
  - "$TRAVIS_BUILD_DIR/vendor/bin/robo $JOB"
  - cd web/themes/custom/nypl_emulsify
  - npm install
  - "./node_modules/gulp/bin/gulp.js build"
  - rm -rf $HOME/web/themes/custom/nypl_emulsify/pattern-lab
  - rm -rf $HOME/web/themes/custom/nypl_emulsify/node_modules

after_success:
  - cd $TRAVIS_BUILD_DIR
  - rm -f Robofile.php
  - provisioning/travis/build_for_aws.sh
  - provisioning/travis/deploy_on_aws.sh
  - provisioning/travis/deploy_to_pantheon.sh

after_failure:
  - if [ -f $HOME/server.log ] ; then echo "Server log:" && cat $HOME/server.log ; fi

after_script:
  - rm -f $HOME/server.log

notifications:
  email:
    recipients: gregorykallenberg@nypl.org
    on_success: always
    on_failure: always
