language: php
dist: trusty
sudo: false

services:
  - docker

php:
  - 7.2
  - 7.3

env:
  global:
    - COMPOSER_MEMORY_LIMIT=2G
    - SIMPLETEST_BASE_URL=http://127.0.0.1:8080
    - SIMPLETEST_DB_URL=mysql://tmp/mysql
    - NODE_VERSION=7.x
    - REMOTE_IMAGE_URL=491147561046.dkr.ecr.us-east-1.amazonaws.com/nypldrupal_phpnginx
    - secure: Te+O+aNZnkBWcKjxx6vIDWR8frujKUXErCFOsCaPGcgA4DRQQ2byBocQaZoXHFMzuNJhunMrPRcGiyOEo21lAmMAGaK3QU6sPJ+8ojU2rXObSFElMlm2CgC3UNusY5wmTWsJqsx1IjByeifIFRaL9pF0yY0ICgR31mBFVPDxok2lcAlj60E1qy+CloW8p7b3Sfm80fiCDTKf6RYWYrIrZ+T4Nl5shqspYbebVRfFsNvTqIIaTmzLFQUBKsDBXg+EpU4h5FG6TKDU4o/ey8F00MLD3bihv2tT2O6Lo6FbSwb3rkAf5/Vm45yAG9NXUq35B2rRPmj+TS8LpKRH4eTXaVjpqYr6bABo5JP7IY/vgiMnTk1A+LX0oY2kEToQR8ZD80omcSzVU3EFOthNkj09jxBOsiRJp9fGYoHExREVCYW47C0Ae+8iZQZbPCUxJrbtYiScmMGjG7ZMP30usUsCoO1lhgcb3GEbiK/jgD3HRGXr0JyGkMkjpftHhMAGesZtI0qcDdYng/yYD/YUiTd/R12KCG4GB49Dh2ldjVRQLZFyT5BHSDU7iGqy/dVYQ6imDA2Ibd5Zgl56MDyGZA1YAHs1UMaiyeKdEUaUI8D5bLCE0D2/3XSQH+vB1qlNX1OZjxgEVNdOV5icbz9IUxUKtcxhTuUOLlkMkipeyEuPP7o=
  matrix:
    - JOB=job:check-coding-standards
    # - JOB=job:run-unit-tests
    # - JOB=job:run-behat-tests

before_install:
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update --$COMPOSER_CHANNEL
  - composer --version
  - sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -
  - sudo apt-get install -y nodejs

install:
  - composer --verbose validate
  - composer --verbose install --prefer-dist --no-interaction

before_script:
  - cp .travis/RoboFile.php .
  - cp .travis/.env .

script:
  - vendor/bin/robo $JOB
  - cd web/themes/custom/nypl_emulsify
  - npm install
  - ./node_modules/gulp/bin/gulp.js build

after_success:
  - cd $TRAVIS_BUILD_DIR
  - provisioning/travis/build_for_aws.sh
  - provisioning/travis/deploy_on_aws.sh

after_failure:
  - if [ -f $HOME/server.log ] ; then echo "Server log:" && cat $HOME/server.log ; fi

after_script:
  - rm -rf $HOME/server.log
  - rm -rf $HOME/web/themes/custom/nypl_emulsify/pattern-lab
  - rm -rf $HOME/web/themes/custom/nypl_emulsify/node_modules

notifications:
  email:
    recipients:
      gregorykallenberg@nypl.org
    on_success: always
    on_failure: always
