version: "3.4"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: "${PROJECT_NAME}_web"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
    ports:
      - 8080:80
    volumes:
      - web:/var/www/html

  mysql:
    image: mysql:5.7
    container_name: "${PROJECT_NAME}_mysql"
    stop_grace_period: 30s
    restart: always
    depends_on:
      - web
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    ports:
      - 3307:3306
    volumes:
      - ./mysqldb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
      - ./mysql:/var/lib/mysql

volumes:
  web:
