version: '3.4'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.build
    container_name: "${PROJECT_NAME}_phpfpm"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_SERVER_ROOT: /var/www/html/web
    env_file:
      - ./.env
    ports:
      - "8080:80"
    volumes:
      - ./config/sync:/etc/nginx/conf.d
    networks:
      - proxy

networks:
  proxy:
